apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    app: example-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: example-service
    version: blue