apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello
        track: stable
        version: blue
    spec:
      containers:
        - name: hello
          image: saeinlee/docker-sample:blue
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 1
  selector:
    matchLabels: