<<<<<<< HEAD
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello
  annotations:
    kubernetes.io/ingress.class: treafik
spec:
  rules:
    - host: dely.com
      http:
        paths:
          -  backend:
              serviceName: hello-green
=======
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello
  annotations:
    kubernetes.io/ingress.class: treafik
spec:
  rules:
    - host: dely.com
      http:
        paths:
          -  backend:
              serviceName: hello-green
>>>>>>> cf11248137102dc93e01ed3b915ea84b88e6e2de
              servicePort: 8081