<<<<<<< HEAD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-bemily-file
  labels:
    node_tag: file
    color: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      node_tag: file
      color: blue
  template:
    metadata:
      labels:
        node_tag: file
        color: blue
    spec:
      containers:
        - name: prod-bemily-file
          image: 193033533370.dkr.ecr.ap-northeast-2.amazonaws.com/bemily/bemily-file-prod:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 38080
          resources:
            requests:
              memory: "2300Mi"
              cpu: "500m"
            limits:
              memory: "2500Mi"
              cpu: "700m"
      nodeSelector:
        node_tag: file
=======
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-blue
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello
        track: stable
        version: blue
    spec:
      containers:
        - name: hello
          image: saeinlee/docker-sample:blue
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: 8081
              path: /readiness
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
  selector:
    matchLabels:
      app: hello
>>>>>>> cf11248137102dc93e01ed3b915ea84b88e6e2de
