<<<<<<< HEAD
apiVersion: v1
kind: Service
metadata:
  name: hello-blue
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      targetPort: http
  selector:
    app: hello
    version: blue
=======
apiVersion: v1
kind: Service
metadata:
  name: hello-blue
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      targetPort: http
  selector:
    app: hello
    version: blue
>>>>>>> cf11248137102dc93e01ed3b915ea84b88e6e2de
